### ISSUE TITLE
Contribute zh-cn WIKI

### ISSUE THREAD

**Issue by Hanamizu2002** [Zeranny/ezedits-wiki#2]
I would like to contribute a Chinese version of ezedits-wiki. At present, I have completed a part of it. Can I submit pull requests directly?

**Comment by Hanamizu2002** [comment]
https://github.com/Hanamizu2002/ezedits-wiki-chinese

**Comment by Zeranny** [comment]
Hey, the only way I could find to have multiple languages was to use collections
I have added your work to the live wiki: https://ezedits.gitbook.io/ezedits/v/zh_cn

For changes, you can submit a PR to https://github.com/Zeranny/ezedits-wiki-zh

Thanks for doing this :)
